### PR TITLE
Fix the problem that directly setting ConfigFilePathENV does not take…

### PR DESCRIPTION
**Pull request by wenchezhao**
… effect

# What does this PR do? 
Fix the problem that directly setting ConfigFilePathENV does not take effect

# Motivation 
Use ConfigFilePathENV to specify the configfile path

# Additional Notes

### CODE REVIEW

**Comment by jeessy2** [comment]
If both parameters and environment variables exist, parameters should be used. Environment variables are internal and not documented.

**Comment by wenchezhao** [comment]
> If both parameters and environment variables exist, parameters should be used. Environment variables are internal and not documented.

for this situation, adjustments were made to use the -c path

**Comment by jeessy2** [comment]
Keep it as it is; it will affect the service.

**Comment by wenchezhao** [comment]
> it will affect the service.

If -c is set, use the -c path. If env is available, use the env path. Otherwise, use the default path. why will it affect the service?

**Comment by jeessy2** [comment]
`ConfigFilePathENV` is internal, do not change the logic to use the variable.

**Comment by wenchezhao** [comment]
> `ConfigFilePathENV` is internal, do not change the logic to use the variable.

projects like kubernetes, etcd ... can use env to specify parameters. it can be specified in a variety of ways to be more friendly.

**Comment by jeessy2** [comment]
alright, It must be compatible with the previous service.

**Comment by jeessy2** [comment]
but other parameters are also not retrieved from environment

**Comment by wenchezhao** [comment]
> alright, It must be compatible with the previous service.

I've done some testing and there's no problem

**Comment by wenchezhao** [comment]
> but other parameters are also not retrieved from environment

Custom configuration file path uses the most commonly used parameters for users. other parameters can be added if necessary

**Comment by jeessy2** [comment]
> > but other parameters are also not retrieved from environment
> 
> Custom configuration file path uses the most commonly used parameters for users. other parameters can be added if necessary

Keep passing parameters only through args and temporarily do not consider retrieving them from environment variables.
Keep it simple.

**Comment by wenchezhao** [comment]
ok

**Pull request closed without merging**
